"""Portfolio source adapters."""

from ppa.sources.base import (
    GallerySource,
    SourceAuthenticationError,
    SourceAuthorizationError,
    SourceError,
    SourceNotFoundError,
    SourceNotImplementedError,
    SourcePreviewCancelledError,
    SourcePreviewDecodeError,
    SourcePreviewDimensionMismatchError,
    SourcePreviewDimensionsTooLargeError,
    SourcePreviewOriginalRejectedError,
    SourcePreviewPayloadTooLargeError,
    SourcePreviewUnavailableError,
    SourcePreviewUnsupportedContentTypeError,
    SourceRateLimitError,
    SourceTransientError,
)
from ppa.sources.loader import load_portfolio
from ppa.sources.preview import (
    PRODUCTION_PREVIEW_MAXIMUM_BYTES,
    PRODUCTION_PREVIEW_MAXIMUM_EDGE,
    CancellationCheck,
    PreviewMetadata,
    PreviewRequest,
    PreviewResource,
    PreviewStorageMode,
)

__all__ = [
    "PRODUCTION_PREVIEW_MAXIMUM_BYTES",
    "PRODUCTION_PREVIEW_MAXIMUM_EDGE",
    "CancellationCheck",
    "GallerySource",
    "PreviewMetadata",
    "PreviewRequest",
    "PreviewResource",
    "PreviewStorageMode",
    "SourceAuthenticationError",
    "SourceAuthorizationError",
    "SourceError",
    "SourceNotFoundError",
    "SourceNotImplementedError",
    "SourcePreviewCancelledError",
    "SourcePreviewDecodeError",
    "SourcePreviewDimensionMismatchError",
    "SourcePreviewDimensionsTooLargeError",
    "SourcePreviewOriginalRejectedError",
    "SourcePreviewPayloadTooLargeError",
    "SourcePreviewUnavailableError",
    "SourcePreviewUnsupportedContentTypeError",
    "SourceRateLimitError",
    "SourceTransientError",
    "load_portfolio",
]
